### ISSUE TITLE
Roadmap for v3

### ISSUE THREAD

**Issue by baseballyama** [sveltejs/eslint-plugin-svelte#966]
## Version 2 (Current Major Version)

- **Svelte Support**:  
  - Support for Svelte 3 and 4  
  - Experimental support for Svelte 5
- **ESLint Support**:  
  - Targeting ESLint v7 and above
- **Node.js Support**:  
  - Requires Node.js v14.17 and above

## Version 3 (Work in Progress)

- [x] **Svelte Support**:  
  - [x] Continued support for Svelte 3 and 4  
  - [x] Full (non-experimental) support for Svelte 5
- [x] **ESLint Support**:  
  - [x] Requires ESLint v8.57.1 or above (https://github.com/sveltejs/eslint-plugin-svelte/pull/937)
- [x] **Node.js Support**:  
  - [x] Requires Node.js v18.20.4 or above (https://github.com/sveltejs/eslint-plugin-svelte/pull/885)
- [x] Update versioning policy (https://github.com/sveltejs/eslint-plugin-svelte/pull/964)
- [x] **Configurations**:  
  - [x] Update recommended config
    - [x] https://github.com/sveltejs/eslint-plugin-svelte/pull/980
    - [x] https://github.com/sveltejs/eslint-plugin-svelte/issues/894
    - [x] https://github.com/sveltejs/eslint-plugin-svelte/pull/1033
- [x] Respect warningFilter setting from Svelte 5 (https://github.com/sveltejs/eslint-plugin-svelte/issues/905)
- [ ] Update README (https://github.com/sveltejs/eslint-plugin-svelte/pull/1041)

And issues which has `v3` label.
https://github.com/sveltejs/eslint-plugin-svelte/milestone/1

## Version 4 (In Planning)

- [ ] **Svelte Support**:  
  - [ ] Continued support for Svelte 3 and 4  
  - [ ] Enhanced rules and integrations for Svelte 5
- [ ] **ESLint Support**:  
  - [ ] Targeting ESLint v9 and above
- [ ] **Node.js Support**:  
  - [ ] Requires Node.js v18.20.4 or above
- [ ] **Rule Improvements**:  
  - [ ] Strengthen and refine rules for Svelte 5-specific features
  - [ ] Potential migration guides and rule deprecation notices for older Svelte versions

**Comment by afonsograca** [comment]
👋 
thank you for this. I wanted to ask if there's any improvements regarding ESLint 9 with TypeScript planned for version 3, or if we should still rely on `typescript-eslint-parser-for-extra-files`

**Comment by baseballyama** [comment]
@afonsograca

My understanding is that there hasn’t been any action taken on the `typeScript-eslint` side, so we still need to use `typescript-eslint-parser-for-extra-files`.
Reference: https://github.com/typescript-eslint/typescript-eslint/issues/6532

If you have any additional information, @ota-meshi, I would appreciate your input.

**Comment by afonsograca** [comment]
my interpretation is that the `typeScript-eslint` team believes that this is an external issue to them, that is why https://github.com/typescript-eslint/typescript-eslint/issues/6532 and https://github.com/typescript-eslint/typescript-eslint/issues/2865 being closed, with the latter labelled as `wontfix`.

**Comment by marekdedic** [comment]
A thing that I don't see mentioned in any of the v3 config update issues/PRs is that maybe it's time to add some rules to the recommended config that weren't recommended before (and maybe some should be dropped)? Should there be a separate issue for that as well?

**Comment by baseballyama** [comment]
I intended to treat that as part of the “Update recommended config” task.

**Comment by baseballyama** [comment]
Since v3 has been released, I will close this issue for now. If we plan for v4, please create a new issue.
